'use client';
import { useEffect, useState } from 'react';
import Nav from '@/components/Nav';
import { Sparkles, RotateCcw, ArrowRight } from 'lucide-react';

export default function QuizPage(){
 const [topic,setTopic]=useState('Physics'); const [qs,setQs]=useState([]); const [answers,setAnswers]=useState({}); const [score,setScore]=useState(null); const [loading,setLoading]=useState(false); const [sourceCount,setSourceCount]=useState(0);
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get('topic'); if(q)setTopic(q)},[]);
 const generate=async()=>{setLoading(true);setScore(null);try{const r=await fetch('/api/quiz',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,count:5})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Generation failed');setQs(j.questions||[]);setSourceCount(j.sources?.length||0);setAnswers({});}catch(e){alert(e.message)}finally{setLoading(false)}};
 const check=async()=>{if(qs.some((q,i)=>answers[i]===undefined)) return alert('Please answer every question.'); const correct=qs.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0);setScore(correct); await fetch('/api/mock-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'quiz',questions:qs,answers:qs.map((_,i)=>answers[i] ?? -1),topic})});};
 return <><Nav/><main className="dashboard-main"><div className="container page"><div className="page-title"><div><div className="eyebrow">Active recall</div><h1>AI Quiz</h1><p className="muted">Generate questions from your uploaded study materials and turn mistakes into weak topics.</p></div></div><div className="card quiz-config"><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic, e.g. Electrochemistry"/><button className="btn btn-primary" onClick={generate}><Sparkles size={16}/>{loading?'Generating…':'Generate 5 questions'}</button>{qs.length>0&&<button className="btn btn-secondary" onClick={check}>Submit Quiz <ArrowRight size={16}/></button>} {sourceCount>0&&<span className="muted source-pill">{sourceCount} source chunks used</span>}</div>{score!==null&&<div className="card result-banner"><div><div className="eyebrow">Result</div><h2>{score}/{qs.length}</h2><p>{score===qs.length?'Excellent — keep the streak alive.':'Review the wrong answers and practice the weak topic below.'}</p></div><button className="btn btn-secondary" onClick={()=>{setQs([]);setScore(null);setAnswers({})}}><RotateCcw size={16}/> New quiz</button></div>}{qs.map((q,idx)=><div className="card question-card" key={idx}><div className="question-meta"><span>Q{idx+1}</span><span>{q.topic||topic}</span></div><strong>{q.question}</strong>{q.options.map((o,oi)=><button key={oi} className={`option ${answers[idx]===oi?'selected':''} ${score!==null&&oi===q.answer?'correct':''} ${score!==null&&answers[idx]===oi&&oi!==q.answer?'wrong':''}`} onClick={()=>score===null&&setAnswers(a=>({...a,[idx]:oi}))}>{o}</button>)}{score!==null&&<p className="muted" style={{marginBottom:0}}>Explanation: {q.explanation}</p>}</div>)}{!qs.length&&<div className="empty card">Choose a topic and generate your first quiz. Upload a PDF first for source-grounded questions.</div>}</div></main></>;
}
