'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Eye, EyeOff, GraduationCap, Sparkles } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function RegisterPage() {
  const router = useRouter();
  const [form, setForm] = useState({ name:'', email:'', password:'', confirm:'' });
  const [show, setShow] = useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e) { e.preventDefault(); setError(''); if(form.password!==form.confirm){setError('Passwords do not match.');return;} setLoading(true); const res=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.name,email:form.email,password:form.password})}); const data=await res.json(); if(!res.ok){setError(data.error||'Registration failed.');setLoading(false);return;} router.push('/onboarding'); router.refresh(); }
  return <main className="auth-shell"><div className="auth-orb orb-one"/><div className="auth-orb orb-two"/><section className="auth-brand-side"><Link href="/" className="logo logo-light"><GraduationCap size={28}/>Padh<span>AI</span></Link><div className="auth-brand-copy"><span className="badge badge-light"><Sparkles size={14}/> Built for every learner</span><h1>Start your <em>smarter</em> preparation.</h1><p>Create one account and let PadhAI turn your study materials into a learning system.</p><div className="auth-points"><div>✓ Choose your exam & subjects</div><div>✓ Get a personalized study plan</div><div>✓ Learn, practice and improve</div></div></div></section><section className="auth-card-wrap"><div className="auth-card"><div className="auth-card-head"><div className="brand-mark">P<span>AI</span></div><h2>Create your account</h2><p>Start your smart preparation today.</p></div><form onSubmit={submit} className="form-stack"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your full name"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<div className="input-with-icon"><input required minLength={8} type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 8 characters"/><button type="button" className="icon-button" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label>Confirm password<input required type={show?'text':'password'} value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} placeholder="Confirm your password"/></label>{error&&<div className="form-error">{error}</div>}<button className="btn btn-primary btn-full" disabled={loading}>{loading?'Creating account...':'Create Account'}</button></form><p className="auth-bottom">Already have an account? <Link href="/login">Login</Link></p></div></section></main>;
}
