import Link from 'next/link';
import { Check, ArrowRight, Sparkles } from 'lucide-react';

const plans = [
  { name: 'Free', price: 'NPR 0', note: 'Explore the full learning loop', items: ['3 study materials', '20 AI questions / month', '3 quizzes / month', '1 mock test / month'] },
  { name: 'Student Pro', price: 'NPR 199', suffix: '/month', note: 'Best for daily preparation', featured: true, items: ['Unlimited study materials', '300 AI questions / month', 'Unlimited quizzes & flashcards', '10 mock tests / month', 'Weak-topic study plan'] },
  { name: 'Exam Pass', price: 'NPR 999', suffix: '/3 months', note: 'Best for an intensive exam season', items: ['Everything in Pro', 'Unlimited mock tests', 'Advanced progress insights', 'Exam-focused revision loop'] },
];
export default function PricingPage(){return <main><header className="header"><div className="container nav"><Link href="/" className="logo">Padh<span>AI</span></Link><Link href="/register" className="btn btn-primary">Start free <ArrowRight size={16}/></Link></div></header><section className="section container pricing-page"><div className="section-intro"><span className="badge"><Sparkles size={14}/> Student pricing</span><h1>Choose your preparation plan</h1><p className="muted">The paid tiers are designed around the value of replacing fragmented study tools with one personalized workspace.</p></div><div className="pricing-grid">{plans.map(plan=><div className={`pricing-card ${plan.featured?'featured':''}`} key={plan.name}>{plan.featured&&<div className="pricing-popular">Most practical</div>}<span className="pricing-name">{plan.name}</span><div className="pricing-price">{plan.price}<small>{plan.suffix}</small></div><p className="muted">{plan.note}</p><div className="pricing-items">{plan.items.map(x=><div key={x}><Check size={16}/><span>{x}</span></div>)}</div><Link href="/register" className={`btn ${plan.featured?'btn-primary':'btn-secondary'} btn-full`}>Start</Link></div>)}</div><div className="pricing-economics card"><h2>Why NPR 199/month?</h2><p className="muted">The Pro price is intentionally below the cost of many fragmented prep subscriptions while leaving room to cover model calls, database, storage and monitoring. Usage caps and retrieval-first prompts help keep variable AI cost predictable.</p><div className="economics-grid"><div><strong>Value</strong><span>One workspace for tutor + practice + revision</span></div><div><strong>Cost control</strong><span>Capped free usage and smaller models for routine tasks</span></div><div><strong>Growth</strong><span>School, coaching and institutional plans can follow</span></div></div></div></section></main>}
