'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Nav from '@/components/Nav';
import { UploadCloud, Trash2, MessageCircle, Sparkles, Layers3, Loader2, FileText } from 'lucide-react';

export default function Materials(){
 const [docs,setDocs]=useState([]),[file,setFile]=useState(null),[title,setTitle]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(false);
 const load=async()=>{const r=await fetch('/api/documents');const j=await r.json();setDocs(j.documents||[])};
 useEffect(()=>{load()},[]);
 const upload=async e=>{e.preventDefault();if(!file)return setStatus('Choose a PDF first.');setLoading(true);setStatus('Reading and indexing your PDF…');const fd=new FormData();fd.append('file',file);fd.append('title',title||file.name);try{const r=await fetch('/api/documents',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw Error(j.error);setStatus(`✓ ${j.chunks} chunks indexed. Your material is ready.`);setFile(null);setTitle('');e.target.reset();load()}catch(err){setStatus(err.message)}finally{setLoading(false)}};
 const remove=async id=>{if(!confirm('Delete this material?'))return;const r=await fetch(`/api/documents?id=${id}`,{method:'DELETE'});const j=await r.json();if(!r.ok)return alert(j.error);load()};
 return <><Nav/><main className="dashboard-main"><div className="container page"><div className="page-title"><div><div className="eyebrow">Your knowledge base</div><h1>Study materials</h1><p className="muted">Upload the sources PadhAI should use for tutoring, summaries, quizzes and flashcards.</p></div></div>
 <div className="grid" style={{gridTemplateColumns:'minmax(320px,.8fr) 1.2fr',alignItems:'start'}}><form className="card" onSubmit={upload}><h3>Add a material</h3><p className="muted">Text-based PDFs up to 10MB are supported.</p><div className="file-drop"><UploadCloud size={30} style={{color:'#635bff'}}/><div style={{marginTop:10,fontWeight:800}}>{file?file.name:'Choose a PDF'}</div><small className="muted">Your source stays tied to your account.</small><br/><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Material title (optional)" style={{width:'100%',marginTop:12,padding:12,border:'1px solid #d0d5dd',borderRadius:10}}/><button className="btn btn-primary" style={{marginTop:12}} disabled={loading} type="submit">{loading?<><Loader2 className="spin" size={16}/>Indexing…</>:<><UploadCloud size={16}/>Upload & index</>}</button>{status&&<p className={status.startsWith('✓')?'badge-success':'muted'} style={{marginTop:12}}>{status}</p>}</form>
 <div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h3>Your library</h3><p className="muted" style={{marginTop:4}}>{docs.length} material{docs.length===1?'':'s'} ready</p></div><Link className="btn btn-secondary btn-sm" href="/chat"><MessageCircle size={14}/> Ask AI</Link></div>
 {docs.length?docs.map(d=><div key={d.id} className="card card-hover" style={{padding:16,marginTop:12,boxShadow:'none'}}><div style={{display:'flex',gap:12,alignItems:'flex-start'}}><div className="feature-icon" style={{flexShrink:0}}><FileText size={18}/></div><div style={{minWidth:0,flex:1}}><strong>{d.title}</strong><div className="muted" style={{fontSize:12,marginTop:3}}>{d.fileName} • {new Date(d.createdAt).toLocaleDateString()}</div><p className="muted" style={{fontSize:13,lineHeight:1.5}}>{d.preview}…</p><div className="doc-actions"><Link className="btn btn-secondary btn-sm" href={`/chat?document=${d.id}`}><MessageCircle size={14}/> Chat</Link><Link className="btn btn-secondary btn-sm" href={`/summary?topic=${encodeURIComponent(d.title)}`}><Sparkles size={14}/> Summary</Link><Link className="btn btn-secondary btn-sm" href={`/flashcards?topic=${encodeURIComponent(d.title)}`}><Layers3 size={14}/> Cards</Link><button className="btn btn-secondary btn-sm" onClick={()=>remove(d.id)}><Trash2 size={14}/> Delete</button></div></div></div></div>):<div className="empty">No materials yet. Upload your first PDF to unlock source-grounded AI.</div>}</div></div>
 </div></main></>;
}
